routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('products', App\Http\Controllers\ProductController::class);

Route::resource('productAgents', App\Http\Controllers\ProductAgentController::class);

Route::resource('categories', App\Http\Controllers\CategoryController::class);

app/Models/ProductAgent.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ProductAgent
 * @package App\Models
 * @version October 20, 2020, 10:31 am UTC
 *
 * @property integer $master_product_id
 * @property integer $agent_id
 * @property number $price_big
 * @property number $price_medium
 * @property number $price_small
 * @property string $alias_name
 * @property string $alias_sku
 * @property boolean $is_active
 * @property string $start_date
 * @property string $end_date
 * @property integer $pieceInBox
 * @property integer $created_by
 * @property integer $updated_by
 */
class ProductAgent extends Model
{
    use SoftDeletes;

    public $table = 'product_agent';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'master_product_id',
        'agent_id',
        'price_big',
        'price_medium',
        'price_small',
        'alias_name',
        'alias_sku',
        'is_active',
        'start_date',
        'end_date',
        'pieceInBox',
        'created_by',
        'updated_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'master_product_id' => 'integer',
        'agent_id' => 'integer',
        'price_big' => 'decimal:2',
        'price_medium' => 'decimal:2',
        'price_small' => 'decimal:2',
        'alias_name' => 'string',
        'alias_sku' => 'string',
        'is_active' => 'boolean',
        'start_date' => 'date',
        'end_date' => 'date',
        'pieceInBox' => 'integer',
        'created_by' => 'integer',
        'updated_by' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'master_product_id' => 'nullable|integer',
        'agent_id' => 'nullable|integer',
        'price_big' => 'nullable|numeric',
        'price_medium' => 'nullable|numeric',
        'price_small' => 'nullable|numeric',
        'alias_name' => 'nullable|string|max:191',
        'alias_sku' => 'nullable|string|max:191',
        'is_active' => 'nullable|boolean',
        'start_date' => 'nullable',
        'end_date' => 'nullable',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable',
        'pieceInBox' => 'nullable|integer',
        'created_by' => 'nullable|integer',
        'updated_by' => 'nullable|integer'
    ];

    
}

app/Http/Controllers/ProductAgentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateProductAgentRequest;
use App\Http\Requests\UpdateProductAgentRequest;
use App\Repositories\ProductAgentRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class ProductAgentController extends AppBaseController
{
    /** @var  ProductAgentRepository */
    private $productAgentRepository;

    public function __construct(ProductAgentRepository $productAgentRepo)
    {
        $this->productAgentRepository = $productAgentRepo;
    }

    /**
     * Display a listing of the ProductAgent.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $productAgents = $this->productAgentRepository->all();

        return view('product_agents.index')
            ->with('productAgents', $productAgents);
    }

    /**
     * Show the form for creating a new ProductAgent.
     *
     * @return Response
     */
    public function create()
    {
        return view('product_agents.create');
    }

    /**
     * Store a newly created ProductAgent in storage.
     *
     * @param CreateProductAgentRequest $request
     *
     * @return Response
     */
    public function store(CreateProductAgentRequest $request)
    {
        $input = $request->all();

        $productAgent = $this->productAgentRepository->create($input);

        Flash::success('Product Agent saved successfully.');

        return redirect(route('productAgents.index'));
    }

    /**
     * Display the specified ProductAgent.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $productAgent = $this->productAgentRepository->find($id);

        if (empty($productAgent)) {
            Flash::error('Product Agent not found');

            return redirect(route('productAgents.index'));
        }

        return view('product_agents.show')->with('productAgent', $productAgent);
    }

    /**
     * Show the form for editing the specified ProductAgent.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $productAgent = $this->productAgentRepository->find($id);

        if (empty($productAgent)) {
            Flash::error('Product Agent not found');

            return redirect(route('productAgents.index'));
        }

        return view('product_agents.edit')->with('productAgent', $productAgent);
    }

    /**
     * Update the specified ProductAgent in storage.
     *
     * @param int $id
     * @param UpdateProductAgentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProductAgentRequest $request)
    {
        $productAgent = $this->productAgentRepository->find($id);

        if (empty($productAgent)) {
            Flash::error('Product Agent not found');

            return redirect(route('productAgents.index'));
        }

        $productAgent = $this->productAgentRepository->update($request->all(), $id);

        Flash::success('Product Agent updated successfully.');

        return redirect(route('productAgents.index'));
    }

    /**
     * Remove the specified ProductAgent from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $productAgent = $this->productAgentRepository->find($id);

        if (empty($productAgent)) {
            Flash::error('Product Agent not found');

            return redirect(route('productAgents.index'));
        }

        $this->productAgentRepository->delete($id);

        Flash::success('Product Agent deleted successfully.');

        return redirect(route('productAgents.index'));
    }
}

resources/views/product_agents/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Agent
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'productAgents.store']) !!}

                        @include('product_agents.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_agents/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Agent
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($productAgent, ['route' => ['productAgents.update', $productAgent->id], 'method' => 'patch']) !!}

                        @include('product_agents.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/product_agents/fields.blade.php
<!-- Master Product Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('master_product_id', 'Master Product Id:') !!}
    {!! Form::number('master_product_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Agent Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('agent_id', 'Agent Id:') !!}
    {!! Form::number('agent_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Price Big Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price_big', 'Price Big:') !!}
    {!! Form::number('price_big', null, ['class' => 'form-control']) !!}
</div>

<!-- Price Medium Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price_medium', 'Price Medium:') !!}
    {!! Form::number('price_medium', null, ['class' => 'form-control']) !!}
</div>

<!-- Price Small Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price_small', 'Price Small:') !!}
    {!! Form::number('price_small', null, ['class' => 'form-control']) !!}
</div>

<!-- Alias Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('alias_name', 'Alias Name:') !!}
    {!! Form::text('alias_name', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Alias Sku Field -->
<div class="form-group col-sm-6">
    {!! Form::label('alias_sku', 'Alias Sku:') !!}
    {!! Form::text('alias_sku', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Is Active Field -->
<div class="form-group col-sm-6">
    {!! Form::label('is_active', 'Is Active:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('is_active', 0) !!}
        {!! Form::checkbox('is_active', '1', null) !!}
    </label>
</div>


<!-- Start Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('start_date', 'Start Date:') !!}
    {!! Form::text('start_date', null, ['class' => 'form-control','id'=>'start_date']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#start_date').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- End Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('end_date', 'End Date:') !!}
    {!! Form::text('end_date', null, ['class' => 'form-control','id'=>'end_date']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#end_date').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Pieceinbox Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pieceInBox', 'Pieceinbox:') !!}
    {!! Form::number('pieceInBox', null, ['class' => 'form-control']) !!}
</div>

<!-- Created By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_by', 'Created By:') !!}
    {!! Form::number('created_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Updated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_by', 'Updated By:') !!}
    {!! Form::number('updated_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('productAgents.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/product_agents/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Product Agents</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('productAgents.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('product_agents.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/product_agents/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product Agent
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('product_agents.show_fields')
                    <a href="{{ route('productAgents.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_agents/show_fields.blade.php
<!-- Master Product Id Field -->
<div class="form-group">
    {!! Form::label('master_product_id', 'Master Product Id:') !!}
    <p>{{ $productAgent->master_product_id }}</p>
</div>

<!-- Agent Id Field -->
<div class="form-group">
    {!! Form::label('agent_id', 'Agent Id:') !!}
    <p>{{ $productAgent->agent_id }}</p>
</div>

<!-- Price Big Field -->
<div class="form-group">
    {!! Form::label('price_big', 'Price Big:') !!}
    <p>{{ $productAgent->price_big }}</p>
</div>

<!-- Price Medium Field -->
<div class="form-group">
    {!! Form::label('price_medium', 'Price Medium:') !!}
    <p>{{ $productAgent->price_medium }}</p>
</div>

<!-- Price Small Field -->
<div class="form-group">
    {!! Form::label('price_small', 'Price Small:') !!}
    <p>{{ $productAgent->price_small }}</p>
</div>

<!-- Alias Name Field -->
<div class="form-group">
    {!! Form::label('alias_name', 'Alias Name:') !!}
    <p>{{ $productAgent->alias_name }}</p>
</div>

<!-- Alias Sku Field -->
<div class="form-group">
    {!! Form::label('alias_sku', 'Alias Sku:') !!}
    <p>{{ $productAgent->alias_sku }}</p>
</div>

<!-- Is Active Field -->
<div class="form-group">
    {!! Form::label('is_active', 'Is Active:') !!}
    <p>{{ $productAgent->is_active }}</p>
</div>

<!-- Start Date Field -->
<div class="form-group">
    {!! Form::label('start_date', 'Start Date:') !!}
    <p>{{ $productAgent->start_date }}</p>
</div>

<!-- End Date Field -->
<div class="form-group">
    {!! Form::label('end_date', 'End Date:') !!}
    <p>{{ $productAgent->end_date }}</p>
</div>

<!-- Pieceinbox Field -->
<div class="form-group">
    {!! Form::label('pieceInBox', 'Pieceinbox:') !!}
    <p>{{ $productAgent->pieceInBox }}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{{ $productAgent->created_by }}</p>
</div>

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{{ $productAgent->updated_by }}</p>
</div>

resources/views/product_agents/table.blade.php
<div class="table-responsive">
    <table class="table" id="productAgents-table">
        <thead>
            <tr>
                <th>Master Product Id</th>
        <th>Agent Id</th>
        <th>Price Big</th>
        <th>Price Medium</th>
        <th>Price Small</th>
        <th>Alias Name</th>
        <th>Alias Sku</th>
        <th>Is Active</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Pieceinbox</th>
        <th>Created By</th>
        <th>Updated By</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($productAgents as $productAgent)
            <tr>
                <td>{{ $productAgent->master_product_id }}</td>
            <td>{{ $productAgent->agent_id }}</td>
            <td>{{ $productAgent->price_big }}</td>
            <td>{{ $productAgent->price_medium }}</td>
            <td>{{ $productAgent->price_small }}</td>
            <td>{{ $productAgent->alias_name }}</td>
            <td>{{ $productAgent->alias_sku }}</td>
            <td>{{ $productAgent->is_active }}</td>
            <td>{{ $productAgent->start_date }}</td>
            <td>{{ $productAgent->end_date }}</td>
            <td>{{ $productAgent->pieceInBox }}</td>
            <td>{{ $productAgent->created_by }}</td>
            <td>{{ $productAgent->updated_by }}</td>
                <td>
                    {!! Form::open(['route' => ['productAgents.destroy', $productAgent->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('productAgents.show', [$productAgent->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('productAgents.edit', [$productAgent->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>